version: '3'
services:
  server:
    build: ./
    ports:
      - 8081:8081
    environment:
      SERVER_ADDRESS: 0.0.0.0:8081
      ENV: local
      DB_SOURCE: postgres://user:pass@postgresql:5432/shortlinks?sslmode=disable
    depends_on:
      migrate:
        condition: service_completed_successfully

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shortlinks
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: pg_isready -U user -d shortlinks
      interval: 5s
      timeout: 3s
      retries: 3

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path=/migrations/", "-database=postgresql://user:pass@postgresql:5432/shortlinks?sslmode=disable", "up"]
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  postgres-data: