// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	shortlinks "github.com/GrishaSkurikhin/OzonTestTask/internal/service/shortlinks"
)

// ServiceURLGetter is an autogenerated mock type for the ServiceURLGetter type
type ServiceURLGetter struct {
	mock.Mock
}

// GetURL provides a mock function with given fields: ctx, shortURL, getter
func (_m *ServiceURLGetter) GetURL(ctx context.Context, shortURL string, getter shortlinks.URLGetter) (string, error) {
	ret := _m.Called(ctx, shortURL, getter)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, shortlinks.URLGetter) (string, error)); ok {
		return rf(ctx, shortURL, getter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, shortlinks.URLGetter) string); ok {
		r0 = rf(ctx, shortURL, getter)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, shortlinks.URLGetter) error); ok {
		r1 = rf(ctx, shortURL, getter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewServiceURLGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceURLGetter creates a new instance of ServiceURLGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceURLGetter(t mockConstructorTestingTNewServiceURLGetter) *ServiceURLGetter {
	mock := &ServiceURLGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
